### ISSUE TITLE
signal passed vertically without connection

### ISSUE THREAD

**Issue by KindarConrath** [TechnicalitiesMC/SuperCircuitMaker#1]
Minecraft: 1.18.1
Forge: 39.0.8
SCM2: 0.0.3
Tested with other mods: just JEI
![2021-12-23_20 05 19](https://user-images.githubusercontent.com/5119861/147303937-1c06f70a-42eb-4618-9492-3fcb11593532.png)
![2021-12-23_20 06 14](https://user-images.githubusercontent.com/5119861/147303938-14d3a9fc-0792-415d-9e9b-6c60acce2800.png)

**Comment by amadornes** [comment]
The fix will be available in the next build, which will go live later today.

It's not a perfect solution and I'll want to re-visit the way a couple things work with regards to this, but it solves the problem for now.

**Comment by amadornes** [comment]
I've been out of town for the past few days, so sorry for the delay in releasing a new build.

v0.1.0 is now live with the fix:  
**CurseForge:** https://mc-mods.cf/super-circuit-maker/files/3581169  
**GitHub:** https://github.com/TechnicalitiesMC/SuperCircuitMaker/releases/tag/v0.1.0
